export const Municipalities = [
  {
    id: "1",
    name: "بلدية غزة",
    name_en: "Gaza Municipality",
    neighborhoods: [
      {
        id: 1,
        name: "حي الرمال",
        name_en: "Al-Rimal Neighborhood",
        latitude: "31.5200000",
        longitude: "34.4500000",
      },
      {
        id: 2,
        name: "حي الشجاعية",
        name_en: "Al-Shujayea Neighborhood",
        latitude: "31.5100000",
        longitude: "34.4700000",
      },
      {
        id: 3,
        name: "حي التفاح",
        name_en: "Al-Tuffah Neighborhood",
        latitude: "31.5050000",
        longitude: "34.4600000",
      },
      {
        id: 4,
        name: "حي الزيتون",
        name_en: "Al-Zaytoun Neighborhood",
        latitude: "31.4980000",
        longitude: "34.4550000",
      },
      {
        id: 5,
        name: "حي الدرج",
        name_en: "Al-Daraj Neighborhood",
        latitude: "31.5150000",
        longitude: "34.4480000",
      },
      {
        id: 6,
        name: "حي الصبرة",
        name_en: "Al-Sabra Neighborhood",
        latitude: "31.5080000",
        longitude: "34.4420000",
      },
    ],
  },
  {
    id: "2",
    name: "بلدية خان يونس",
    name_en: "Khan Yunis Municipality",
    neighborhoods: [
      {
        id: 7,
        name: "حي مركز المدينة",
        name_en: "City Center Neighborhood",
        latitude: "31.3438050",
        longitude: "34.3028880",
      },
      {
        id: 8,
        name: "حي النصر",
        name_en: "Al Nasir Neighborhood",
        latitude: "31.3645910",
        longitude: "34.2925370",
      },
      {
        id: 9,
        name: "حي الأمل",
        name_en: "AL Amal Neighborhood",
        latitude: "31.3560170",
        longitude: "34.2987240",
      },
      {
        id: 10,
        name: "حي المعسكر",
        name_en: "Khan Younis Camp Neighborhood",
        latitude: "31.3484620",
        longitude: "34.2929170",
      },
      {
        id: 11,
        name: "حي الكتيبة",
        name_en: "AL Katiba Neighborhood",
        latitude: "31.3567240",
        longitude: "34.3071570",
      },
      {
        id: 12,
        name: "حي المحطة",
        name_en: "AL Mahata Neighborhood",
        latitude: "31.3502570",
        longitude: "34.3125770",
      },
      {
        id: 13,
        name: "حي الشيخ ناصر",
        name_en: "Al Sheikh Nasser Neighborhood",
        latitude: "31.3401470",
        longitude: "34.3114970",
      },
    ],
  },
  {
    id: "3",
    name: "بلدية رفح",
    name_en: "Rafah Municipality",
    neighborhoods: [
      {
        id: 14,
        name: "حي السلام",
        name_en: "AL Salam Neighborhood",
        latitude: "31.3032010",
        longitude: "34.2932450",
      },
      {
        id: 15,
        name: "حي التحرير",
        name_en: "Al Tahrer Neighborhood",
        latitude: "31.3416460",
        longitude: "34.2714940",
      },
      {
        id: 16,
        name: "حي البرازيل",
        name_en: "Brazil Neighborhood",
        latitude: "31.2950000",
        longitude: "34.2650000",
      },
      {
        id: 17,
        name: "حي الجنينة",
        name_en: "Al-Junaina Neighborhood",
        latitude: "31.2980000",
        longitude: "34.2700000",
      },
      {
        id: 18,
        name: "حي الشابورة",
        name_en: "Al-Shaboura Neighborhood",
        latitude: "31.3010000",
        longitude: "34.2800000",
      },
    ],
  },
  {
    id: "4",
    name: "بلدية جباليا",
    name_en: "Jabalia Municipality",
    neighborhoods: [
      {
        id: 19,
        name: "حي الجلاء",
        name_en: "AL Jla Neighborhood",
        latitude: "31.3779360",
        longitude: "34.3129170",
      },
      {
        id: 20,
        name: "حي السطر",
        name_en: "AL Satar Neighborhood",
        latitude: "31.3637140",
        longitude: "34.3212180",
      },
      {
        id: 21,
        name: "حي الفالوجا",
        name_en: "Al-Faluja Neighborhood",
        latitude: "31.5300000",
        longitude: "34.4800000",
      },
      {
        id: 22,
        name: "حي النزهة",
        name_en: "Al-Nuzha Neighborhood",
        latitude: "31.5280000",
        longitude: "34.4820000",
      },
    ],
  },
  {
    id: "5",
    name: "بلدية دير البلح",
    name_en: "Deir Al-Balah Municipality",
    neighborhoods: [
      {
        id: 23,
        name: "حي المواصي الشمالي",
        name_en: "Northern Mawasi Neighborhood",
        latitude: "31.3789930",
        longitude: "34.2914510",
      },
      {
        id: 24,
        name: "حي المواصي الجنوبي",
        name_en: "Southern Mawasi Neighborhood",
        latitude: "31.3501690",
        longitude: "34.2578560",
      },
      {
        id: 25,
        name: "حي البطن السمين",
        name_en: "Butn Alsameen Neighborhood",
        latitude: "31.3387250",
        longitude: "34.2934920",
      },
      {
        id: 26,
        name: "حي معن",
        name_en: "Maain Neighborhood",
        latitude: "31.3299710",
        longitude: "34.3160700",
      },
    ],
  },
  {
    id: "6",
    name: "بلدية بيت لاهيا",
    name_en: "Beit Lahia Municipality",
    neighborhoods: [
      {
        id: 27,
        name: "حي العودة",
        name_en: "Al-Awda Neighborhood",
        latitude: "31.5500000",
        longitude: "34.4900000",
      },
      {
        id: 28,
        name: "حي الكرامة",
        name_en: "Al-Karama Neighborhood",
        latitude: "31.5480000",
        longitude: "34.4880000",
      },
      {
        id: 29,
        name: "حي الشمال",
        name_en: "Northern Neighborhood",
        latitude: "31.5520000",
        longitude: "34.4920000",
      },
    ],
  },
  {
    id: "7",
    name: "بلدية بيت حانون",
    name_en: "Beit Hanoun Municipality",
    neighborhoods: [
      {
        id: 30,
        name: "حي الشهداء",
        name_en: "Al-Shuhada Neighborhood",
        latitude: "31.5400000",
        longitude: "34.5300000",
      },
      {
        id: 31,
        name: "حي الحرية",
        name_en: "Al-Hurriya Neighborhood",
        latitude: "31.5380000",
        longitude: "34.5280000",
      },
      {
        id: 32,
        name: "حي الجنوب",
        name_en: "Southern Neighborhood",
        latitude: "31.5360000",
        longitude: "34.5260000",
      },
    ],
  },
  {
    id: "8",
    name: "بلدية النصيرات",
    name_en: "Nuseirat Municipality",
    neighborhoods: [
      {
        id: 33,
        name: "حي النصيرات المخيم",
        name_en: "Nuseirat Camp Neighborhood",
        latitude: "31.4400000",
        longitude: "34.3700000",
      },
      {
        id: 34,
        name: "حي الجلاء",
        name_en: "Al-Jalaa Neighborhood",
        latitude: "31.4420000",
        longitude: "34.3720000",
      },
      {
        id: 35,
        name: "حي الوسط",
        name_en: "Central Neighborhood",
        latitude: "31.4380000",
        longitude: "34.3680000",
      },
    ],
  },
  {
    id: "9",
    name: "بلدية البريج",
    name_en: "Bureij Municipality",
    neighborhoods: [
      {
        id: 36,
        name: "حي البريج المخيم",
        name_en: "Bureij Camp Neighborhood",
        latitude: "31.4600000",
        longitude: "34.3800000",
      },
      {
        id: 37,
        name: "حي الشرق",
        name_en: "Eastern Neighborhood",
        latitude: "31.4620000",
        longitude: "34.3820000",
      },
    ],
  },
  {
    id: "10",
    name: "بلدية المغازي",
    name_en: "Maghazi Municipality",
    neighborhoods: [
      {
        id: 38,
        name: "حي المغازي المخيم",
        name_en: "Maghazi Camp Neighborhood",
        latitude: "31.4500000",
        longitude: "34.3900000",
      },
      {
        id: 39,
        name: "حي الغرب",
        name_en: "Western Neighborhood",
        latitude: "31.4480000",
        longitude: "34.3880000",
      },
    ],
  },
  {
    id: "11",
    name: "بلدية عبسان الكبيرة",
    name_en: "Abasan Al-Kabira Municipality",
    neighborhoods: [
      {
        id: 40,
        name: "حي عبسان الكبيرة",
        name_en: "Abasan Al-Kabira Neighborhood",
        latitude: "31.3200000",
        longitude: "34.3500000",
      },
      {
        id: 41,
        name: "حي الجنوب",
        name_en: "Southern Neighborhood",
        latitude: "31.3180000",
        longitude: "34.3480000",
      },
    ],
  },
  {
    id: "12",
    name: "بلدية عبسان الصغيرة",
    name_en: "Abasan Al-Jadida Municipality",
    neighborhoods: [
      {
        id: 42,
        name: "حي عبسان الجديدة",
        name_en: "Abasan Al-Jadida Neighborhood",
        latitude: "31.3250000",
        longitude: "34.3550000",
      },
      {
        id: 43,
        name: "حي الشمال",
        name_en: "Northern Neighborhood",
        latitude: "31.3270000",
        longitude: "34.3570000",
      },
    ],
  },
  {
    id: "13",
    name: "بلدية بني سهيلا",
    name_en: "Bani Suheila Municipality",
    neighborhoods: [
      {
        id: 44,
        name: "حي بني سهيلا",
        name_en: "Bani Suheila Neighborhood",
        latitude: "31.3350000",
        longitude: "34.3600000",
      },
      {
        id: 45,
        name: "حي الزهراء",
        name_en: "Al-Zahraa Neighborhood",
        latitude: "31.3370000",
        longitude: "34.3620000",
      },
    ],
  },
  {
    id: "14",
    name: "بلدية القرارة",
    name_en: "Al-Qarara Municipality",
    neighborhoods: [
      {
        id: 46,
        name: "حي القرارة",
        name_en: "Al-Qarara Neighborhood",
        latitude: "31.3450000",
        longitude: "34.3300000",
      },
      {
        id: 47,
        name: "حي الوسط",
        name_en: "Central Neighborhood",
        latitude: "31.3430000",
        longitude: "34.3280000",
      },
    ],
  },
  {
    id: "15",
    name: "بلدية خزاعة",
    name_en: "Khuza'a Municipality",
    neighborhoods: [
      {
        id: 48,
        name: "حي خزاعة",
        name_en: "Khuza'a Neighborhood",
        latitude: "31.3150000",
        longitude: "34.3400000",
      },
      {
        id: 49,
        name: "حي الشرق",
        name_en: "Eastern Neighborhood",
        latitude: "31.3130000",
        longitude: "34.3420000",
      },
    ],
  },
  {
    id: "16",
    name: "بلدية المسراوية",
    name_en: "Al-Masriya Municipality",
    neighborhoods: [
      {
        id: 50,
        name: "حي المسراوية",
        name_en: "Al-Masriya Neighborhood",
        latitude: "31.3550000",
        longitude: "34.2800000",
      },
    ],
  },
  {
    id: "17",
    name: "بلدية قيزان النجار",
    name_en: "Qizan Al-Najjar Municipality",
    neighborhoods: [
      {
        id: 51,
        name: "حي قيزان النجار",
        name_en: "Gizan Alnajar Neighborhood",
        latitude: "31.3200560",
        longitude: "34.2937270",
      },
    ],
  },
  {
    id: "18",
    name: "بلدية قيزان أبو رشوان",
    name_en: "Qizan Abu Rashwan Municipality",
    neighborhoods: [
      {
        id: 52,
        name: "حي قيزان أبو رشوان",
        name_en: "Gizan Abu Rishawn Neighborhood",
        latitude: "31.3289200",
        longitude: "34.2830640",
      },
    ],
  },
  {
    id: "19",
    name: "بلدية الفخاري",
    name_en: "Al-Fukhari Municipality",
    neighborhoods: [
      {
        id: 53,
        name: "حي الفخاري",
        name_en: "Al-Fukhari Neighborhood",
        latitude: "31.3100000",
        longitude: "34.3200000",
      },
      {
        id: 54,
        name: "حي الفردوس",
        name_en: "Al-Firdaws Neighborhood",
        latitude: "31.3080000",
        longitude: "34.3180000",
      },
    ],
  },
  {
    id: "20",
    name: "بلدية الشوكة",
    name_en: "Al-Shawka Municipality",
    neighborhoods: [
      {
        id: 55,
        name: "حي الشوكة",
        name_en: "Al-Shawka Neighborhood",
        latitude: "31.3050000",
        longitude: "34.3100000",
      },
    ],
  },
  {
    id: "21",
    name: "بلدية تل السلطان",
    name_en: "Tel Al-Sultan Municipality",
    neighborhoods: [
      {
        id: 56,
        name: "حي تل السلطان",
        name_en: "Tel Al-Sultan Neighborhood",
        latitude: "31.2900000",
        longitude: "34.2600000",
      },
      {
        id: 57,
        name: "حي المطار",
        name_en: "Airport Neighborhood",
        latitude: "31.2920000",
        longitude: "34.2620000",
      },
    ],
  },
  {
    id: "22",
    name: "بلدية الشابورة",
    name_en: "Al-Shaboura Municipality",
    neighborhoods: [
      {
        id: 58,
        name: "حي الشابورة المخيم",
        name_en: "Al-Shaboura Camp Neighborhood",
        latitude: "31.2980000",
        longitude: "34.2680000",
      },
      {
        id: 59,
        name: "حي الشابورة البلد",
        name_en: "Al-Shaboura Town Neighborhood",
        latitude: "31.2960000",
        longitude: "34.2660000",
      },
    ],
  },
  {
    id: "23",
    name: "بلدية البرازيل",
    name_en: "Brazil Municipality",
    neighborhoods: [
      {
        id: 60,
        name: "حي البرازيل الشمالي",
        name_en: "Brazil North Neighborhood",
        latitude: "31.2940000",
        longitude: "34.2640000",
      },
      {
        id: 61,
        name: "حي البرازيل الجنوبي",
        name_en: "Brazil South Neighborhood",
        latitude: "31.2920000",
        longitude: "34.2620000",
      },
    ],
  },
  {
    id: "24",
    name: "بلدية حي السلام",
    name_en: "Hay Al-Salam Municipality",
    neighborhoods: [
      {
        id: 62,
        name: "حي السلام الشمالي",
        name_en: "Hay Al-Salam North Neighborhood",
        latitude: "31.3032010",
        longitude: "34.2932450",
      },
      {
        id: 63,
        name: "حي السلام الجنوبي",
        name_en: "Hay Al-Salam South Neighborhood",
        latitude: "31.3010000",
        longitude: "34.2910000",
      },
    ],
  },
];
