export enum ReportStatus {
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  NEED_COMPLETION = "NEED_COMPLETION",
  PRE_APPROVED = "PRE_APPROVED",
  REJECTED = "REJECTED",
  FIELD_VERIFICATION_REQUIRED = "FIELD_VERIFICATION_REQUIRED",
  FIELD_VERIFICATION_IN_PROGRESS = "FIELD_VERIFICATION_IN_PROGRESS",
  FIELD_VERIFIED = "FIELD_VERIFIED",
  APPROVED = "APPROVED",
  ESCALATED = "ESCALATED",
}
